arch: arm64
language: node_js

node_js:
  - "10.13.0"
  - "10.14.0"
  - "10.14.1"
  - "10.14.2"
  - "10.15.0"
  - "10.15.1"
  - "10.15.2"
  - "10.15.3"
  - "10.16.0"
  - "10.16.1"
  - "10.16.2"
  - "10.16.3"
  - "10.17.0"
  - "10.18.0"
  - "10.18.1"
  - "10.19.0"
  - "10.20.0"
  - "10.20.1"
  - "10.21.0"
  - "10.22.0"
  - "10.22.1"

cache: false

before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update
  - sudo apt-get -y install libreoffice
  - sudo apt-get -y install libreoffice-pdfimport

install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
  - "npm install ep_hash_auth"

script: "tests/frontend/travis/runnerBackend.sh"
