dist: xenial
language: node_js

node_js:
  - "10.13"

cache: false

jobs:
  include:
    # we can only frontend tests from the ether/ organization and not from forks.
    # To request tests to be run ask a maintainer to fork your repo to ether/
    - if: fork = false
      name: "Test SSL"
      install:
        - "openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 1 -nodes -subj '/CN=localhost'"
        - "./bin/installDeps.sh"
        - "echo '{\"ssl\":{\"key\":\"key.pem\",\"cert\":\"cert.pem\"}}' >settings.json"
        - "node src/node/server.js&"
      script:
        - "wget --no-check-certificate https://localhost:9001/p/test"
