language: node_js

node_js:
  - "10.13.0"
  - "10.14.0"
  - "10.14.1"
  - "10.14.2"
  - "10.15.0"
  - "10.15.1"
  - "10.15.2"
  - "10.15.3"
  - "10.16.0"
  - "10.16.1"
  - "10.16.2"
  - "10.16.3"
  - "10.17.0"
  - "10.18.0"
  - "10.18.1"
  - "10.19.0"
  - "10.20.0"
  - "10.20.1"
  - "10.21.0"
  - "10.22.0"
  - "10.22.1"


services:
  - docker

cache: false

before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update
  - sudo apt-get -y install libreoffice
  - sudo apt-get -y install libreoffice-pdfimport

install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
  - "npm install ep_hash_auth"

script:
  - "tests/frontend/travis/runner.sh"

env:
  global:
    - secure: "WMGxFkOeTTlhWB+ChMucRtIqVmMbwzYdNHuHQjKCcj8HBEPdZLfCuK/kf4rG\nVLcLQiIsyllqzNhBGVHG1nyqWr0/LTm8JRqSCDDVIhpyzp9KpCJQQJG2Uwjk\n6/HIJJh/wbxsEdLNV2crYU/EiVO3A4Bq0YTHUlbhUqG3mSCr5Ec="
    - secure: "gejXUAHYscbR6Bodw35XexpToqWkv2ifeECsbeEmjaLkYzXmUUNWJGknKSu7\nEUsSfQV8w+hxApr1Z+jNqk9aX3K1I4btL3cwk2trnNI8XRAvu1c1Iv60eerI\nkE82Rsd5lwUaMEh+/HoL8ztFCZamVndoNgX7HWp5J/NRZZMmh4g="

jobs:
  include:
    # we can only frontend tests from the ether/ organization and not from forks.
    # To request tests to be run ask a maintainer to fork your repo to ether/
    - if: fork = false
    - name: "Run the Backend tests"
      install:
        - "bin/installDeps.sh"
        - "cd src && npm install && cd -"
      script:
        - "tests/frontend/travis/runnerBackend.sh"

notifications:
  irc:
    channels:
      - "irc.freenode.org#etherpad-lite-dev"
